services:
  resourcespace:
    build: .
    container_name: resourcespace
    restart: unless-stopped
    depends_on:
      - resourcespace-db
    volumes:
      - /mnt/large_storage/resourcespace:/var/www/html/filestore
      - ./config.php:/var/www/html/include/config.php
    networks:
      - resourcespace-net
    ports:
      - "8085:80"

  resourcespace-db:
    image: mariadb:10.11
    container_name: resourcespace-db
    restart: unless-stopped
    env_file:
      - db.env
    volumes:
      - resourcespace_db_data:/var/lib/mysql
    networks:
      - resourcespace-net

networks:
  resourcespace-net:

volumes:
  resourcespace_db_data:
